apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend
        image: mern-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/mern"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30040    # Puerto para acceso externo
  type: NodePort
