apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend
        image: mern-backend
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: mongodb://mongo:27017/mern-crud
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
