apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
      - name: frontend
        image: mern-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  selector:
    app: mern-frontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
    nodePort: 30080  # o el que quieras usar para acceder desde el host
  type: NodePort
