apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
      - name: frontend
        image: mern-frontend
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  selector:
    app: mern-frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 31178
  type: NodePort
